# Generated by Django 4.2.2 on 2023-06-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('applied_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
